shell = "zsh"

[plugins]

# Load zsh plugins in a deferred manner
[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.evalcache]
github = "mroth/evalcache"

[plugins.spaceship]
github = "spaceship-prompt/spaceship-prompt"

# Because we just love commacd
[plugins.commacd]
github = "shyiko/commacd"
use = ["commacd.sh"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-completion]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.zsh-autoenv]
github = "Tarrasch/zsh-autoenv"

[plugins.abbr]
github = "olets/zsh-abbr"
use = ["zsh-abbr.zsh"]

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"
